blog/posts/forms.py
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, URL


class CreatePostForm(FlaskForm):
    """When registered user wants to post about something, this form is used"""
    heading = StringField("Heading", validators=[DataRequired("Cannot have empty heading."), Length(max=50, message="Cannot be more than 50 words.")])
    description = StringField("Description", validators=[DataRequired("Cannot post without providing description."), Length(max=240, message="Cannot be more than 240 words")])
    post_image = StringField("Post Image URL", validators=[DataRequired("Cannot post without a URL."), URL()])
    content = CKEditorField("Content", validators=[DataRequired("Cannot post with empty content."), Length(min=1, message="Cannot create a empty post.")])
    submit = SubmitField("Create Post")


class CommentForm(FlaskForm):
    comment = CKEditorField("Content", validators=[DataRequired("Cannot post with empty content."), Length(min=1, message="Cannot create a empty post.")])
    submit_comment = SubmitField("Create Post")

blog/users/forms.py
from blog import db
from blog.models import User
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, EmailField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError


class RegistrationForm(FlaskForm):
    """Form used when user wants to register/ sign-up in our app"""
    username = StringField("Username", validators=[DataRequired(message="Provide username. Field cannot be empty."), Length(max=20, message="Max Length of 20.")])
    email = EmailField("Email", validators=[DataRequired(message="Provide Email. Field cannot be empty."), Email(message="Please enter a valid E-mail Address")])
    password = PasswordField("Password", validators=[DataRequired(message="Cannot be empty.")])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(message="Cannot be empty."), EqualTo("password", message="Must match password.")])
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = db.session.execute(db.select(User).filter_by(username=username.data)).scalar_one_or_none()
        if user:
            raise ValidationError(message="Username is already registered. Please try to sign in.")
        
    def validate_email(self, email):
        user = db.session.execute(db.select(User).filter_by(email=email.data)).scalar_one_or_none()
        if user:
            raise ValidationError("Email is already registered. Please try to sign in.")


class LoginForm(FlaskForm):
    """Form used for user login purposes"""
    email = EmailField("Email", validators=[DataRequired(message="Provide Email for Login."), Email(message="Please enter a valid E-mail Address")])
    password = PasswordField("Password", validators=[DataRequired(message="Cannot be empty.")])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Sign In")


class UpdateUserForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(message="Provide username. Field cannot be empty."), Length(max=20, message="Max Length of 20.")])
    email = EmailField("Email", validators=[DataRequired(message="Provide Email. Field cannot be empty."), Email(message="Please enter a valid E-mail Address")])
    profile_image = FileField("Upload Profile Image", validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField("Update profile")

    def validate_username(self, username):
        if current_user.username != username.data:
            user = db.session.execute(db.select(User).where(User.username==username.data)).scalar_one_or_none()
            if user:
                raise ValidationError("Username is already taken. Please try a different name.")
            
    def validate_email(self, email):
        if current_user.email != email.data:
            user = db.session.execute(db.select(User).where(User.email==email.data)).scalar_one_or_none()
            if user:
                raise ValidationError("Email is already taken. Please try a different name.")


class ResetRequest(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(message="Provide Email for Login."), Email(message="Please enter a valid E-mail Address")])
    submit = SubmitField("Confirm Password")

    def validate_email(self, email):
        user = db.session.execute(db.select(User).where(User.email==email.data)).scalar_one_or_none()
        if user is None:
            raise ValidationError("Email is not registered. Please try again.")


class ResetPasswordForm(FlaskForm):
    password = PasswordField("Password", validators=[DataRequired(message="Cannot be empty.")])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(message="Cannot be empty."), EqualTo("password", message="Must match password.")])
    submit = SubmitField("Confirm Password")

blog/main/routes.py
from blog import db, login_manager
from blog.models import User, Post
from flask import render_template, request, Blueprint

main = Blueprint("main", __name__)


@login_manager.user_loader
def load_user(user_id):
	return db.get_or_404(User, user_id)


@main.route("/")
def home():
	page = request.args.get("page", 1, type=int)
	posts = db.paginate(db.select(Post).order_by(Post.date_posted.desc()), page=page, per_page=5)
	return render_template("home.html", pagetitle="HomePage", posts=posts)


@main.route("/about")
def about():
	return render_template("about.html")


@main.route("/contact")
def contact():
	return render_template("contact.html")


@main.route("/filter_post/<name>")
def filter_post(name):
	user_data = db.session.execute(db.select(User).where(User.username==name)).scalar()
	page = request.args.get("page", 1, type=int)
	get_single_users_posts = db.paginate(db.select(Post).filter_by(author_id=user_data.id).order_by(Post.date_posted.desc()), page=page, per_page=5)
	return render_template("home.html", posts=get_single_users_posts, filter=True, name=name)

blog/posts/routes.py
from blog import db
from blog.posts.forms import CreatePostForm, CommentForm
from blog.models import Post, Comment
from flask import flash, render_template, redirect, request, url_for, abort, Blueprint
from flask_login import login_required, current_user

posts = Blueprint("posts", __name__)

@posts.route("/post", methods=["GET", "POST"])
@login_required
def post():
	form = CreatePostForm()
	if form.validate_on_submit():
		new_post = Post(
			title=form.heading.data,
			description=form.description.data,
			post_image=form.post_image.data,
			content=form.content.data,
			author=current_user
		)
		db.session.add(new_post)
		db.session.commit()
		return redirect(url_for("main.home"))
	return render_template("create_post.html", form=form, value="Create")


@posts.route("/update_post/<int:post_id>", methods=["GET", "POST"])
@login_required
def update_post(post_id):
	form = CreatePostForm()
	post = db.session.execute(db.select(Post).where(Post.id==post_id)).scalar_one_or_none()
	if post is None:
		abort(404)
	if current_user.id != post.author_id:
		abort(401)
	if form.validate_on_submit():
		post.title = form.heading.data
		post.description = form.description.data
		post.post_image = form.post_image.data
		post.content = form.content.data
		db.session.commit()
		flash("Your post has been updated", "success")
		return redirect(url_for("posts.show_post", post_id=post.id))
	form.heading.data = post.title
	form.description.data = post.description
	form.post_image.data = post.post_image
	form.content.data = post.content
	return render_template("create_post.html", form=form, post=post, value="Update")


@posts.route("/delete_post/<int:post_id>")
@login_required
def delete_post(post_id):
	post = db.session.execute(db.select(Post).where(Post.id==post_id)).scalar()
	if current_user.id != post.author_id:
		abort(401)
	db.session.delete(post)
	db.session.commit()
	flash("Your post has been successfully deleted", "success")
	return redirect(url_for("main.home"))


@posts.route("/show_post/<int:post_id>", methods=["GET", "POST"])
def show_post(post_id):
	post = db.session.execute(db.select(Post).where(Post.id==post_id)).scalar()
	if not post:
		flash("Invalid input provided.", "warning")
		return redirect(url_for("main.home"))
	form = CommentForm()
	comment_page = request.args.get("page", 1, type=int)
	comments = db.paginate(db.select(Comment).where(Comment.post_id==post_id), page=comment_page, per_page=5)
	if form.validate_on_submit():
		new_comment = Comment(
			description=form.comment.data,
			user=current_user,
			feedback=post
		)
		db.session.add(new_comment)
		db.session.commit()
		return redirect(url_for("posts.show_post", post_id=post.id))
	return render_template("post.html", post=post, date=post.date_posted.strftime("%Y-%m-%d"), form=form, comments=comments)

blog/users/routes.py
from blog import bcrypt, db
from blog.users.forms import RegistrationForm, LoginForm, UpdateUserForm, ResetPasswordForm, ResetRequest
from blog.models import User
from flask import flash, render_template, redirect, request, url_for, Blueprint
from flask_login import login_user, logout_user, current_user
from blog.users.utilities import save_profile_pictures, send_reset_mail

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
	form = RegistrationForm()
	# Checks whether the user is logged in or not
	if current_user.is_authenticated:
		flash("You are already logged in", "info")
		return redirect(url_for("main.home"))
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
		new_user = User(
			username=form.username.data,
			email=form.email.data,
			password=hashed_password
		)
		db.session.add(new_user)
		db.session.commit()
		flash(message="You have registered successfully", category="success")
		return redirect(url_for("users.login"))
	return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
	form = LoginForm()
	# Checks whether the user is logged in or not
	if current_user.is_authenticated:
		flash("You are already logged in", "info")
		return redirect(url_for("main.home"))
	if form.validate_on_submit():
		email = form.email.data
		user = db.session.execute(db.select(User).where(User.email==email)).scalar()
		if user:
			if bcrypt.check_password_hash(user.password, form.password.data):
				login_user(user, remember=form.remember.data)
				return redirect(url_for("main.home"))
			else:
				flash("Incorrect Email/ Password provided. Please check user credentials.", "danger")
				return redirect(url_for("users.login"))	
		else:
			flash("User not registered. Please register here.", "warning")
			return redirect(url_for("users.register"))
	return render_template("login.html", form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("main.home"))


@users.route("/profile", methods=["GET", "POST"])
def profile():
	form = UpdateUserForm()
	# Checks whether the user is not logged in.
	if not current_user.is_authenticated:
		flash("You cannot access this page before logging in.", "warning")
		return redirect(url_for("users.login"))
	if form.validate_on_submit():
		if form.profile_image.data:
			new_profile_photo = save_profile_pictures(form.profile_image.data)
			current_user.profile_photo = new_profile_photo
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash("Your profile has been updated", "success")
		return redirect(url_for("users.profile"))
	elif request.method == "GET":
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.profile_photo)
	return render_template("profile.html", form=form, image_file=image_file)


@users.route("/reset_request", methods=["GET", "POST"])
def reset_request():
	# Checks whether the user is logged in or not
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))
	form = ResetRequest()
	if form.validate_on_submit():
		user = db.session.execute(db.select(User).where(User.email==form.email.data)).scalar_one_or_none()
		if user:
			send_reset_mail(user)
			flash("A mail has successfully been send to your email.", "success")
			return redirect(url_for("users.login"))
		else:
			flash("Invalid input. Provided email not registered.")
			return redirect(url_for("users.register"))
	return render_template("reset_request.html", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
	# Checks whether the user is logged in or not
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))
	user = User.verify_reset_token(token)
	if user is None:
		flash("This is a invalid or expired link", "warning")
		return redirect(url_for("users.login"))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hash_password = bcrypt.generate_password_hash(form.password.data)
		user.password = hash_password
		db.session.commit()
		flash("Your password has successfully updated. Please try to login.", "success")
		return redirect(url_for("users.login"))
	return render_template("reset_password.html", form=form)

blog/templates/comment.html
{% if current_user.is_authenticated %}
<!-- Comment form -->
<div class="container w-50">
    <div class="position-relative text-muted">
        <div class="w-50 mx-auto d-flex flex-column">
            <main class="form-signin align-self-center">
                <form action="" method="POST" novalidate>
                    <fieldset class="form-group">
                        {{ form.hidden_tag() }}
                        <legend class="bottom-border text-center">Comments</legend>

                        <!-- Content Section -->
                        <div class="form-group">
                            {{ form.comment(class_="form-control") }}
                        </div>
                        {{ form.submit_comment(class_="btn btn-primary w-100 py-1 mt-1", value="Submit") }}
                    </fieldset>
                </form>
                {{ ckeditor.load() }}
                {{ ckeditor.config(name="content", height=100) }}
            </main>
        </div>
    </div>
</div>
{% endif %}

{% if comments.total != 0%}
<div class="container col-7 my-5">
    <div
        class="position-relative text-muted bg-body border border-dashed rounded-5 shadow py-2 mb-5 bg-body-tertiary row justify-content-md-center">

        {% for comment in comments %}
        <div class="col-5 d-flex flex-column">
            <img src="{{ url_for('static', filename='profile_pics/' + comment.user.profile_photo) }}" alt="mdo" id="comment_img"
                class="mx-auto">
            <a href="{{ url_for('main.filter_post', name=comment.user.username) }}"
                class="link-body-emphasis text-center text-decoration-none" aria-expanded="false">
                {{ comment.user.username }}
            </a>
        </div>

        <div class="col-7">
            <p class="fs-3">{{ comment.description|safe }}</p>
        </div>
        <hr class="w-75">
        <br>
        {% endfor %}

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                {% if comments.has_prev %}
                <a class="page-link" href="{{ url_for('posts.show_post', post_id=post.id, page=comments.prev_num) }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
                {% else %}
                <a class="page-link disabled" href="{{ url_for('posts.show_post', post_id=post.id, page=comments.prev_num) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                {% endif %}
              </li>
              {% for page_num in comments.iter_pages(left_edge=1, left_current=1, right_current=1, right_edge=1) %}
              {% if page_num != comments.page %}
              <li class="page-item"><a class="page-link" href="{{ url_for('posts.show_post', post_id=post.id, page=page_num) }}">{{ page_num }}</a></li>
              {% else %}
              <li class="page-item"><a class="page-link disabled" href="{{ url_for('posts.show_post', post_id=post.id, page=page_num) }}">{{ page_num }}</a></li>
              {% endif %}
              {% endfor %}
              <li class="page-item">
                {% if comments.has_next %}
                <a class="page-link" href="{{ url_for('posts.show_post', post_id=post.id, page=comments.next_num) }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
                {% else %}
                <a class="page-link disabled" href="{{ url_for('posts.show_post', post_id=post.id, page=comments.next_num) }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
              </li>
            </ul>
          </nav>
    </div>
</div>
{% endif %}

<div class="container my-5"></div>
</div>

blog/templates/delete_modal.html
<!-- Delete Button Modal - Confirmation before deleting the post -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete this post?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="GET">
                    <button type="submit" class="btn btn-danger">Delete Post</button>
                </form>
            </div>
        </div>
    </div>
</div>

blog/templates/home.html
{% extends "layout.html" %}

{% block header %}
<div class="container-fluid text-center border rounded" id="home-bg">
    <div class="home-header-bg container-fluid h-100"></div>
    <div class="container position-absolute top-50 start-50 translate-middle home-header-text">
        {% if filter %}
        <h1 class="fs-1">{{ name }} Post's</h1>
        {% else %}
            {% if current_user.is_authenticated %}
            <h1 class="fs-1">Welcome {{ current_user.username }}</h1>
            {% else %}
            <h1 class="fs-1">Welcome</h1>
            {% endif %}
            <p class="col-lg-8 mx-auto lead font-monospace">Share your experience of CS50.</p>
            <div class=" container mx-auto rounded home-header-p-bg">
                <p class=" home-header-p">Share your high and low times, how you recovered. What's your plan next after
                    completing
                    CS50? </p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock header %}

{% block content %}
<div class="container col-7 my-5">

    {% for post in posts.items %}
    <div
        class="position-relative text-muted bg-body border border-dashed rounded-5 shadow py-5 mb-5 bg-body-tertiary row justify-content-md-center">
        <div class="col-auto d-flex flex-column">
            <img src="{{ url_for('static', filename='profile_pics/' + post.author.profile_photo) }}" alt="mdo" id="img" class="mt-4 mx-auto">
            <a href="{{ url_for('main.filter_post', name=post.author.username) }}" class="link-body-emphasis text-center text-decoration-none mt-3" aria-expanded="false">
                {{ post.author.username }}
            </a>
        </div>


        <div class="col-7 mx-5">
            <!-- Button X - Used for deleting post - Post Author Verification -->
            {% if current_user.id == post.author_id %}
            <button type="button"
                class="position-absolute top-0 end-0 p-3 m-3 btn-close bg-secondary bg-opacity-10 rounded-pill"
                aria-label="Close" data-bs-toggle="modal" data-bs-target="#deleteModal"></button>
            {% include "delete_modal.html" %}
            {% endif %}
            <h2 class="text-black">{{ post.title }}</h2>
            <p class="col-6 mb-4 fs-5">{{ post.description}}</p>
            <div class="col d-flex justify-content-end">
                <!-- Update Button - Checks for author verification -->
                {% if current_user.id == post.author_id %}
                <form action="{{ url_for('posts.update_post', post_id=post.id) }}" method="GET">
                    <button class="btn btn-primary px-auto mb-3 mx-2" type="submit">
                        Update
                    </button>
                </form>
                {% endif %}
                <form action="{{ url_for('posts.show_post', post_id=post.id) }}" method="GET">
                    <button class="btn btn-primary px-auto mb-3" type="submit">
                        Know More
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg justify-content-center">
      <li class="page-item">
        {% if posts.has_prev %}
        <a class="page-link" href="{{ url_for('main.home', page=posts.prev_num) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        {% else %}
        <a class="page-link disabled" href="{{ url_for('main.home', page=posts.prev_num) }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        {% endif %}
      </li>
      {% for page_num in posts.iter_pages(left_edge=1, left_current=1, right_current=1, right_edge=1) %}
      {% if page_num != posts.page %}
      <li class="page-item"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link disabled" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
      {% endif %}
      {% endfor %}
      <li class="page-item">
        {% if posts.has_next %}
        <a class="page-link" href="{{ url_for('main.home', page=posts.next_num) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        {% else %}
        <a class="page-link disabled" href="{{ url_for('main.home', page=posts.next_num) }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </nav>

{% endblock content %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% if pagetitle %}
        <title>My Blog - {{ pagetitle }}</title>
        {% else %}
        <title>My Blog</title>
        {% endif %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>

    <body>

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">

                <a class="navbar-brand" href="{{ url_for('main.home') }}">CS50 Diary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item"> <!-- After login option -->
                            <a class="nav-link" href="{{ url_for('posts.post') }}">New Post</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}">About Me</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.contact') }}">Contact Us</a>
                        </li>
                    </ul>
                    {% if current_user.is_authenticated %}
                    <!-- Show after user login -->
                    <div class="dropstart text-end">
                        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ url_for('static', filename='profile_pics/' + current_user.profile_photo) }}"
                                alt="mdo" width="32" height="32" class="rounded-circle object-fit-cover">
                        </a>
                        <ul class="dropdown-menu text-small">
                            <li><a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('users.logout') }}">Sign out</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <!-- Show if user has not logged in -->
                    <nav class="navbar bg-body-tertiary">
                        <div class="container-fluid">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page"
                                        href="{{ url_for('users.login') }}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page"
                                        href="{{ url_for('users.register') }}">Register</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% block header %}{% endblock header %}

        <!-- Flash messages/ erros as alerts -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} text-center" role="alert"><strong>{{ message }}</strong></div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock content %}

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>
    </body>

</html>

blog/templates/post.html
{% extends "layout.html" %}

{% block header %}
<div class="container-fluid text-center border rounded" id="show-post-bg"
    style="background-image: url('{{ post.post_image }}');">
    <div class="-header-bg container-fluid h-100"></div>
    <div class="container position-absolute top-50 start-50 translate-middle post-header-text">
        <h1 class="fs-1">{{ post.title}}</h1>
        <p class="col-lg-8 mx-auto lead font-monospace"></p>
        <div class=" container mx-auto rounded -header-p-bg">
            <p class="fs-2 post-header-p">{{ post.description }}</p>
        </div>
    </div>
</div>
{% endblock header %}

{% block content %}
<div class="container my-5">
    <div
        class="position-relative text-muted bg-body border-dashed rounded-5 shadow py-5 mb-5 bg-body-tertiary row justify-content-md-center">
        <div class="col-1 d-flex flex-column align-items-center">
                <img src="{{ url_for('static', filename='profile_pics/' + post.author.profile_photo) }}" alt="mdo" id="img">
                <a href="{{ url_for('main.filter_post', name=post.author.username) }}" class="link-body-emphasis text-center text-decoration-none" aria-expanded="false">
                    {{ post.author.username }}
                </a>
        </div>

        <div class="col-6 mx-5">
            <div class="row mx-5">
                <h2 class="text-black">{{ post.title }}</h2>
            </div>

            <div class="row mx-5">
                <p class="mb-4 fs-5">{{ post.description }}</p>
            </div>
        </div>

        <!-- Update & Delete Button - Checks for author verification -->
        <div class="col-3 d-flex flex-column align-items-end">

            {% if current_user.id == post.author_id %}
            <div>
                <form action="{{ url_for('posts.update_post', post_id=post.id) }}" method="GET">
                    <button class="btn btn-primary px-auto" type="submit">
                        Update
                    </button>
                </form>
            </div>
            <div>
                <button type="button" class="btn btn-danger px-3 my-1" data-bs-toggle="modal" data-bs-target="#deleteModal">
                    Delete
                </button>
            </div>
            {% endif %}
        </div>
        <!-- Content of the post -->
            <div class="container mt-5 px-4 px-lg-5">
                <div class="row justify-content-md-center" id="show-post-content">
                    <div class="col-10">
                        {{ post.content|safe }}
                    </div>
                </div>
            </div>
        <!-- Mentioning author and date of the post -->
        <div class="row">
            <div class="col-11 pe-4 text-end">
                <p class="my-4 fs-6">Posted on {{ date }} by {{ post.author.username }}</p>
            </div>
        </div>
    </div>
</div>

{% include "comment.html" %}

{% include "delete_modal.html" %}

{% endblock %}